entrypoint.sh

We run in alpine
PTAL @ibrahim0814 @hootener @codecov/support

Update bash entrypoint

---

README.md

fix python-version in example workflow.yml

---

index.js
package-lock.json
package.json

We are seeing some inconsistency with pulling the bash script, so marking a retry here

Retry retrieval of bash script

---

.github/workflows/main.yml
dist/index.js
index.js
package-lock.json
package.json

Should not need to run `npm install` to use the action

Fix dependencies

---

action.yml

Update action.yml with new authors

---

dist/index.js
index.js
package.json

Depends on https://github.com/codecov/codecov-bash/pull/378

Add package argument

---

README.md

File is saved as text

---

CHANGELOG.md
action.yml
package-lock.json
package.json

Add `network_filter` to `action.yml` so that it can be used by the Action

Add network_filter to manifest

---

dist/index.js
src/buildExec.test.ts
src/buildExec.ts
src/version.ts

Adds the action version along with the bash version

fix: Add action version

---

hooks/pre-commit

Add `set -e` to pre-commit hook

---

action.yml
dist/index.js
hooks/pre-commit
package-lock.json
package.json

- Refactors dependencies as dev deps
- Remove unused deps
- Refactor `pre-commit` hook to not make changes to the files before committing

refactor: dependencies and dev dependencies

---

dist/index.js
src/buildExec.test.ts
src/buildExec.ts

refactor: destructure the assignment of `version`

---

dist/index.js

chore: Fix typo in index.js

---

.github/workflows/scorecards-analysis.yml

The base template of the workflow has changed since it was introduced into this repository.

Regenerate scorecards-analysis.yml

---

README.md

Validate I didn't mess up the meaning

Fix `network` entry in table

---

.github/workflows/main.yml

fixes https://github.com/codecov/codecov-action/issues/1412

fix: prevent xlarge from running on forks

---

.github/workflows/main.yml

fixes https://github.com/codecov/codecov-action/issues/1429

fix: update container builds

---

.github/workflows/main.yml
action.yml

fixes https://github.com/codecov/engineering-team/issues/2935

fix: use double-quotes for OIDC

---

action.yml

Pin actions/github-script by Git SHA

---

dist/codecov.sh

fixes: #1863
If this isn't the correct method of updating the wrapper, I would love to know how and to contribute!

feat: upgrade wrapper to 0.2.4
