- .github/workflows/main.yml
- Dockerfile
Add workflow to repo that tests action locally
Switch to Ubuntu for base since alpine uses BusyBox and and `find` does not have the flags we need for the GCov file search.
> Repo now self-tests

- Dockerfile
- entrypoint.sh
Similar to https://github.com/codecov/codecov-circleci-orb/pull/17
1. `codecov-bash` already handles optional arguments passed to it, so let's not duplicate that work here.
2. Do not exit with a non-zero exit status when upload fails, or even if the token is not set (i.e. in forks / pull requests). This matches the behaviour of the CircleCI orb.
3. Use `debian:stretch-slim` instead of `ubuntu:latest` as base for the Docker image, since it's smaller and forces us to be a more explicit in our dependencies.
4. `COPY` only what we need, and no need to set `WORKDIR`.
> Fix shell command issues

- README.md
- action.yml
- dist/index.js
- index.js
- package.json
Adding some functionality from the bash script and exposing it here. In particular
- specifying a directory to search for coverage reports
- specify a path to save down the coverage report sent to Codecov before uploading
> Add directory and file save

- LICENSE
- dist/index.js
- index.js
- package-lock.json
- package.json
It looks like a lot, but I just indented it and wrapped it all with a try catch to fix. Also bumping to 1.0.12
```
(node:4814) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 35.199.43.247:443
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
(node:4814) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4814) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
> Wrap request promise in try catch

- README.md
- index.js
Supporting Xcode related parameters.
https://docs.codecov.io/docs/about-the-codecov-bash-uploader#arguments
> Support Xcode specificed parameters

- README.md
- action.yml
- index.js
This PR adds an input `working-directory:`, the same name as GitHub Actions uses for generic (`run:`) steps: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun
The value is passed to the `cwd` option of GitHub's @actions/exec exec() method:
https://github.com/actions/toolkit/blob/d9347d4ab99fd507c0b9104b2cf79fb44fcc827d/packages/exec/src/interfaces.ts#L5-L7
This allows the user to specify in which directory codecov.sh should run.
Other information:
- I have looked at #70 and https://github.com/codecov/codecov-action/issues/51#issuecomment-595077546 —this PR differs because it is not trying to address the deprecated/removed `-y` option to `codecov.sh`, but rather allow configuration of the directory in which the program is executed.
- The …
> Add "working-directory:" input

- .github/workflows/main.yml
- dist/index.js
- package-lock.json
- package.json
- src/buildExec.test.ts
- src/buildExec.ts
- src/index.ts
On `pull_request*` events (`pull_request`, `pull_request_target`) using the `actions/checkout` step, GitHub Actions creates a detached HEAD SHA. This SHA is what gets sent to Codecov as opposed to the true HEAD SHA. The change ensures that the underlying uploader receives the correct SHA based on the GitHub context.
This change will allow for usage of this Action without adding `fetch-depth` to the `checkout` step by overwriting the detached SHA with the HEAD SHA
> Overwrite the commit on pull_request* events

- CHANGELOG.md
- dist/index.js
- package-lock.json
- package.json
- src/buildExec.ts
Fixes https://github.com/codecov/codecov-action/issues/155
This PR addresses the issue with `pull_request_target` events and Codecov pulling the wrong PR number. The Action will now force the value to the bash uploader.
> Overwrite pull_request_target pr number

- action.yml
- dist/index.js
- src/index.ts
- src/validate.test.ts
- src/validate.ts
Adds checksum validation for the underlying bash script
fixes https://github.com/codecov/codecov-action/issues/281
> Add checksum verification of bash script

- CHANGELOG.md
- package-lock.json
- package.json
> Bump to 1.4.0

- CHANGELOG.md
- dist/index.js
- package-lock.json
- package.json
- src/index.ts
- src/validate.test.ts
- src/validate.ts
Updates the validation regex to restrict on digits and dots. Adds checksums into the script so that it doesn't do another request. Also bumps to 1.4.1
> Update validation regex, pull checksums into script, and bump to 1.4.1

- dist/codecov
- src/codecov
The current bash uploader is outdated and seems to be the cause of the issues reported in #330. Although I'm by no means certain, I haven't looked into this particularly deeply.
This PR updates the bash uploader to 1.0.3, which is the current version one can fetch from https://codecov.io/bash
Since the script is inlined in this repository, it's probably prudent to put a check in to verify that it's up-to-date, and fail CI if it's not. Is that something you'd want in a PR?
> Update bash uploader to 1.0.3

- CHANGELOG.md
- package-lock.json
- package.json
- #320 doc: add github actions badge
- #336 Update bash uploader to 1.0.3
- #302 Bump @typescript-eslint/eslint-plugin from 4.22.0 to 4.22.1
- #303 Bump @typescript-eslint/parser from 4.22.0 to 4.22.1
- #304 Bump ts-jest from 26.5.5 to 26.5.6
- #309 Bump lodash from 4.17.19 to 4.17.21
- #310 Bump hosted-git-info from 2.8.8 to 2.8.9
- #311 Bump @actions/github from 4.0.0 to 5.0.0
- #314 Bump eslint from 7.25.0 to 7.27.0
- #315 Bump @actions/core from 1.2.7 to 1.3.0
- #316 Bump @typescript-eslint/parser from 4.22.1 to 4.25.0
- #317 Bump @typescript-eslint/eslint-plugin from 4.22.1 to 4.25.0
- #319 Bump jest-junit from 12.0.0 to 12.1.0
- #321 Bump typescript from 4.2.4 to 4.3.2
- #323 Bump ws from 7.3.1 to 7.4.6
- #331 Bump eslint from 7.27.0 to 7.28.0
- #332 Bump @actions/exec from 1.0.4 to …
> Bump to 1.5.1

- CHANGELOG.md
- dist/index.js
- package-lock.json
- package.json
- src/buildExec.test.ts
- src/buildExec.ts
- src/version.ts
Fixes an issue found https://github.com/codecov/codecov-action/issues/330 regarding version coming up as `github-actions-[Object object]`
> fix: Import version properly as string not object

- package-lock.json
- package.json
\@types/node was already *installed* (due to \@types/jest which is dependent on it). \@types/node was likely intended to have been installed alongside it.
Fixes #345
> deps: install @types/node@14.17.3

- dist/index.js
- package-lock.json
This runs `npm run build` with `typescript==4.3.2` which is what is the pinned dependency. Will create some fixes later to make this more automatic on CI.
See https://github.com/codecov/codecov-action/issues/343
> fix: Build with ts-4.3.2

- dist/index.js
- src/buildExec.test.ts
- src/buildExec.ts
- src/index.ts
Since the uploader code is already stored in the action, it doesn't need to write and remove the file anymore.
Fixes https://github.com/codecov/codecov-action/issues/351
Fixes https://github.com/codecov/codecov-action/issues/346
> refactor: remove unneeded codecov copy and unlink

- dist/index.js
- src/buildExec.test.ts
- src/buildExec.ts
- src/version.ts
Fixes https://github.com/codecov/codecov-action/issues/343
Removes the `version.js` file and pulls the version directly from `package.json`
> refactor: Pull version from package.json

- README.md
This PR fixes a small typo in a link to the blog. The incorrect spelling in the href previously landed you on a 404 page.
> Fix wrong link in the readme

- README.md
The deprecation deadline has passed; this PR updates the language to be more accurate.
I also specified the version that was deprecated, since I actually had misunderstood the warning to be saying that "this version" was referring to the entire action itself, and that the guidance was to no longer use the action at all!  I think the new language will help prevent that kind of confusion for others.
> Update deprecation warning

- src/index.ts
- src/validate.ts
This PR resolves https://github.com/codecov/codecov-action/issues/768 by respecting `fail_ci_on_error` when uploader validation fails.
> Plumb failCi into verification function.

- README.md
- src/buildExec.test.ts
> Remove unsupported path_to_write_report argument

- README.md
I've found out after having issues with empty coverage reports that some files searching can be avoided by using negate path.
I've read the code here to understand it: https://github.com/codecov/uploader/blob/bc4b55a694478ac480a1fda4ed030c164c0c5438/src/index.ts#L220
Than I able to fix the action which tried uploading files like: `./yarn/cache/some-dep-coverage.zip`.
> Update README to contain correct information - inputs and negate feature

- action.yml
Node.js 16 actions are deprecated.
This should suppress the deprecation notice:
>Please update the following actions to use Node.js 20: codecov/codecov-action@v3
> action.yml: Update to Node.js 20

- action.yml
Mirroring https://github.com/codecov/codecov-action/pull/1228
Node.js 16 actions are deprecated.
This should suppress the deprecation notice:
> Please update the following actions to use Node.js 20: codecov/codecov-action@v3
> chore(ci): bump to node20

- README.md
Some of the argument descriptions in the "Arguments" table have pipes in them, which the Markdown parser treats as table cell delimiters, leading to incorrect rendering.  This PR escapes the pipes in descriptions, thereby fixing the rendering.
> Escape pipes in table of arguments

- README.md
This adds a link to the relevant docs regarding giving access to the `CODECOV_TOKEN` to Dependabot.
> Add link to docs on Dependabot secrets

- README.md
> [!NOTE]
> GitHub Markdown no longer support `>**Note**:` syntax
GitHub Discussions: https://github.com/orgs/community/discussions/16925
> Use updated syntax for GitHub Markdown notes

- README.md
To my knowledge , none of Codecov's supported code hosts support Mercurial, nor does the CLI itself.
> Removed mention of Mercurial

- src/validate.ts
I am running into the issue #1279, and the message below is not sufficient to diagnose the reason for the error.
```txt
==> macos OS detected
https://cli.codecov.io/latest/macos/codecov.SHA256SUM
==> Running version latest
Error: Codecov: Error importing pgp key
```
> fix: more verbose log message when failing to import pgp key

- src/index.ts
- src/validate.ts
Add the `node:` prefix to imports of node internal packages, making it easier to differentiate
> style: Node Packages

- src/buildExec.test.ts
- src/buildExec.ts
- src/helpers.ts
- src/index.ts
> docs: Type Annotations

- .github/workflows/codeql-analysis.yml
- .github/workflows/enforce-license-compliance.yml
- .github/workflows/scorecards-analysis.yml
- README.md
Rename `master` to `main`.
Note: As the `master` branch is no longer available, both workflows haven't run in the last few months
> docs: main branch

- src/buildExec.ts
This fixes https://github.com/codecov/feedback/issues/358 and #1457 and would greatly improve the situation for everyone using Codecov until https://github.com/codecov/engineering-team/issues/1574 has been solved and released.
Even if the fork provides a Codecov token, it is ignored and tokenless uploading is used.
It adjusts the logic so that an existing token is always used, regardless of whether the PR originates from a fork or not.
> Use an existing token even if the PR is from a fork

- package-lock.json
- package.json
- src/buildExec.ts
This PR adds in a package to give the correct types for GH payload events, as well this PR removes redundant string coercion that's not needed.
> ref: Tidy up types and remove string coercion

- action.yml
https://github.com/codecov/codecov-action/commit/bb7467c2bce05781760a0964d48e35e96ee59505 broke the `disable_safe_directory` input.
While the [input definition](https://github.com/codecov/codecov-action/commit/bb7467c2bce05781760a0964d48e35e96ee59505#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R24-R27) was kept the same, the usage in code was changed from [`disable_safe_directory`](https://github.com/codecov/codecov-action/commit/bb7467c2bce05781760a0964d48e35e96ee59505#diff-340f73bcb6cfc5bb360e31166bd24f415f42d51df477aecb2824c4a34c391f0bL233) to [`set_safe_directory`](https://github.com/codecov/codecov-action/commit/bb7467c2bce05781760a0964d48e35e96ee59505#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R159).
I assume this to be a typo, …
> fix: typo in `inputs.disable_safe_directory`

- README.md
fixes https://github.com/codecov/codecov-action/issues/1652
> fix: bump to v5 and update README

- CHANGELOG.md
- changelog.py
- hooks/pre-commit
fixes https://github.com/codecov/codecov-action/issues/1667
fixes https://github.com/codecov/codecov-action/issues/1658
> fix: update CHANGELOG and automate

- README.md
The table included an erroneous `tional` in its own row that seems to be a left-over mistake from changes to its context.
> Remove mistake from options table

- action.yml
While debugging a "Token required because branch is protected" problem with two of my repositories, I noticed this in the codecov-action logs:
```
if [ "false" == 'true' ];
then
CC_TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://codecov.io" | cut -d\" -f6)
echo "CC_TOKEN=$CC_TOKEN" >> "$GITHUB_ENV"
elif [ -n "" ];
then
echo "CC_TOKEN=" >> "$GITHUB_ENV"
else
if [ -n ***
];
then
CC_TOKEN=$(echo ***
| tr -d '\n')
echo "CC_TOKEN=$CC_TOKEN" >> "$GITHUB_ENV"
fi
fi
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
CARGO_HOME: /home/runner/.cargo
CARGO_INCREMENTAL: 0
CARGO_TERM_COLOR: always
CACHE_ON_FAILURE: false
##[endgroup]
/home/runner/work/_temp/0f1d96ca-0f3a-423c-b405-fa68034346d8.sh: line 10: [: missing …
```
> Put quotes around `${{ inputs.token }}` in `action.yml`

- action.yml
audience should be set to the enterprise url if using oidc authentication with it
> use correct audience when requesting oidc token

- README.md
The current version of the script treats the Python version as a number, leading to the following error:
```
Run actions/setup-python@main
Installed versions
Version 3.1 was not found in the local cache
Error: The version '3.1' with architecture 'x64' was not found for Ubuntu 24.04.
```
To fix this, add quotes to treat the version as a string.
>  Fix a typo in the example

- action.yml
The description stated "testing" was a valid value, but that leads to an error if you try to use it. The error message indicates that the value should be "test_results" instead.
> Fix description for report_type input

- action.yml
Inside a container the actual workspace path is a mount point and not the same as outside the container. E.g.:
- `${{github.workspace}} == /home/runner/work/locale/locale`
- `$GITHUB_WORKSPACE == /__w/locale/locale`
So it seems `/home/runner/work` is mounted at `/__w` and this is reflected by the environment variable but not the context.    So use that variable instead.
Fixes #1767
> Fix use of safe.directory inside containers

- README.md
- action.yml
- https://github.com/codecov/codecov-cli/pull/650 added this arg to the CLI
- https://github.com/codecov/wrapper/pull/48 added it to the bash wrapper
this PR updates the wrapper and adds the arg to the GHA
> update wrapper submodule to 0.2.0, add recurse_submodules arg
